# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  build:
    docker:
    - image: hseeberger/scala-sbt:8u222_1.3.6_2.13.1

    working_directory: ~/repo

    environment:
      # Setting the JVM minimum memory allocation to 256 MB and maximum allocation to 2 GB.
      # java.awt.headless=true: Disabling GUI features because streamee don't use them
      # Dilating durations to account for slower CI environment
      SBT_OPTS: "-Xms256m -Xmx2g -Djava.awt.headless=true"

    steps:
    - checkout
    # Download and cache dependencies
    - restore_cache:
        keys:
        - sbt-v1-deps-{{ checksum "build.sbt" }}
        # fallback to using the latest cache if no exact match is found
        - sbt-v1-deps
    - run:
        name: Running SBT compilation
        command: sbt +test:compile
    - save_cache:
        paths:
        - ~/.m2
        - ~/.ivy2
        - ~/.sbt
        key: sbt-v1-deps-{{ checksum "build.sbt" }}
    - run:
        name: Running tests
        command: sbt -Dakka.test.timefactor=3.0 +test
